name: Run Python Script Daily

on:
  schedule:
    - cron: '0 0 * * *'  # At 00:00 (UTC) every day

jobs:
  run_python_script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # Ensure the Python version matches your needs

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run script
        run: python main.py 
